shotgunsoftware/tk-multi-workfiles2

python/tk_multi_workfiles/entity_tree/entity_tree_proxy_model.py
The left hand side tree view is now sorted alphabetically:
Previously, it would just display the raw data as it was being sent from the shotgun model. The shotgun model does not imply any ordering of the data, this is left to the client to handle (since it typically varies between use cases and sometimes, like in the case of the loader, you want to do a bunch of post processing of the raw model data before you have access to the display name which you want to order by).
=> #38761 Tree view sorted alphabetically

info.yml, python/tk_multi_workfiles/entity_proxy_model.py, python/tk_multi_workfiles/entity_tree/entity_tree_form.py
Previously, workfiles assumed that the tree structure on the left hand side was always fully loaded. The new optimized shotgun model defer loads stuff into memory for performance and this caused workfiles to not get all the child data correctly when an item in the left hand side tree was clicked. 
This fix adds a recursive load of child data just in time before it's needed, ensuring consistent behaviour when running with the new optimized sg model.
The filtering logic has been updated to ensure the entire tree is fetched just in time prior to filtering.
This change is backwards compatible and will not affect users running against older versions of the sg model but it is required if you want to run with the latest optimized version.
=> Changes to workfiles to work with new defer loaded sg model

info.yml, python/tk_multi_workfiles/entity_tree/entity_tree_form.py, python/tk_multi_workfiles/file_form_base.py, python/tk_multi_workfiles/my_tasks/my_tasks_model.py, python/tk_multi_workfiles/util.py
#42449
#42445
#39615
Made some changes that hopefully make working with large amounts of tasks a bit easier.
More work is still needed, but these can be considered quick fixes.
Added option to disable auto expansion of root level in the tree views.
- You can now set a`auto_expand_tree` key on the app config to true or false, to toggle this behaviour
Added option to set a list of status that the My Tasks tab will use as a filter to exclude.
- can now set a config key for `my_tasks_filter_statuses: ['fin','omt']` to filter out tasks from the "my tasks" tab, with the status codes listed.
Changed tree view search box behaviour so that it only performs the search after hitting enter.
This helps when performing the search is very slow, as it will now only perform the search after enter is hit, …
=> #42449 Usability tweaks to improve working with large amounts of tasks

python/tk_multi_workfiles/file_list/file_list_item_delegate.py, python/tk_multi_workfiles/file_list/file_widget.py, python/tk_multi_workfiles/ui/file_widget.py, resources/file_widget.ui
Currently, if filenames exceed approximately 23 characters (varies in Nuke and Maya), the file browser list displays them as truncated names. This sometimes also causes the version information to be hidden. 
eg.
This PR attempts to resolve this issue by making the following layout modifications to the file widget:
* The work file name now displays an ellipsis to indicate that it is longer than it appears to be. The tooltip should show the full name of the file.
* The version is now listed on the following line (instead of comma-separated `name, v001`).
Like so
=> #44390 Modified the file widget layout to account for long filenames.

python/tk_multi_workfiles/actions/interactive_open_action.py
Fixes a bug where if using user sandboxes and a user tries to open a file belonging to another user, when they don't have any files themselves, it will error.
Fix was suggested by Nico Rehberg, Thanks!
=> #45463 Fix for user work area version up.

hooks/scene_operation_tk-photoshopcc.py
The photoshopcc hook handled exceptions raised by the tk-photoshopcc RPC API, but it didn't keep the logged exception from making its way into the console via logging. The Adobe bridge class in the engine does all of this for us via some convenience methods, so this is moving the hook to using those instead of implementing similar logic locally.
=> For #41520: Eliminates noise on app launch in Photoshop.

python/tk_multi_workfiles/entity_models/deferred_model.py, python/tk_multi_workfiles/entity_models/extended_model.py, python/tk_multi_workfiles/entity_tree/entity_tree_form.py
Couple of fixes related to refreshing the model:
* In classic mode, emit a data changed as soon as some cached data is loaded, instead of waiting for the async refresh to trigger a data changed callback.
* Fixed the overlay widget by using the right widget and the right parent.
* Refresh the file browser when no entities are found after a deferred model refresh.
=> For #38483, improved refresh.

python/tk_multi_workfiles/actions/file_action.py
This now makes sure that the while loop properly recursively checks the parent templates, instead of potentially getting stuck in an endless loop. Previously if the statement `template_keys <= ctx_keys` wasn't immediately true, then it would continuously loop forever, causing the DCC to lock up.
This could be replicated by having a `version` folder in your workfiles template something like this:
```
max_asset_work:
definition: '@asset_root/work/3dsmax/v{version}/{name}.v{version}.max'
```
=> SG-6431 Fixes a bug with the new file action

info.yml, python/tk_multi_workfiles/browser_form.py
Addresses PR comments from JF here:
https://github.com/shotgunsoftware/tk-multi-workfiles2/pull/57/files
* allows_empty is now False
* loops over valid tabs and compares against lower() for
configured values.
* warns/raises now if tab names are problematic
=> For #SG-7629: Fixes for PR from BoulderMedia

hooks/workfiles_management.py, python/tk_multi_workfiles/actions/interactive_open_action.py
Create Workfile entities for the following workflows:
- Workfile that gets created when a Published file is opened through the dialog
- Workfile that gets created when a Person copies another Person's workfile into their own sandbox 
Use the 'sg_link' field (instead of 'entity') for Workfiles implemented as custom entities
=> Create Workfiles for additional workflows

hooks/workfiles_management.py, python/tk_multi_workfiles/actions/interactive_open_action.py, python/tk_multi_workfiles/actions/open_file_action.py, python/tk_multi_workfiles/actions/open_publish_actions.py, python/tk_multi_workfiles/actions/open_workfile_actions.py, python/tk_multi_workfiles/file_save_form.py
Takes Amy's fix for sandboxes and generalizes it so any time a workfile is saved a unique version number is generated across sandboxes.
This required a new field to be introduced on the `Workfile` custom entity: `sg_name_field`. This is the value of the name field in the save dialog. I didn't go with simply `sg_name` because I was afraid it would cause confusion between `code`, `name` and `sg_name`.
When moving to this new version of the app, the Workfile entity first need to be migrated to populate that field.
It could be (I haven't actually executed this) as simple as
```
for entity in sg.find("CustomEntity45", []):
fake_sg_publish_data = {
"id": entity["id"],
"path": entity["sg_path"]
}
sgtk.util.resolve_publish_path(sgtk, fake_sg_publish_data);
sg.update(
entity['type'], entity['id'] …
```
=> For SG-10271, unique version number across sandboxes

app.py
This is the change made in #67. We're simply removing use of the `toTuple` method provided by PySide in favor of an approach that will also work with PyQt5.
=> SG-10466: Minor change for PyQt5 compatibility.

info.yml, python/tk_multi_workfiles/actions/file_action_factory.py, python/tk_multi_workfiles/actions/interactive_open_action.py, python/tk_multi_workfiles/actions/open_file_action.py, python/tk_multi_workfiles/actions/open_publish_actions.py, python/tk_multi_workfiles/actions/open_workfile_actions.py
There were several fixes and optimizations done.
- Move the call to `workfiles_management.get_next_workfile_version` outside of the actions as the menu generation slowed down as more and more submenu-items were added.
- Centralized the registration logic deep into the FileOpenAction menu, where files are copied into another sandbox and need to be registered.
- Introduced a new setting that allows to hide publish actions on workfiles and vise-versa
- Clarified the text of actions that copy workfiles into your own sandbox.
=> For SG-10961, small fixes for workfiles management

python/tk_multi_workfiles/actions/file_action.py
This change means the full original error stack gets logged and we still raise an error with a more friendly message.
Previously we would only get the actual error message without a stack trace, which meant the error was too vague, and difficult to track down.
=> SG-11483 improves the error logging when changing context.

python/tk_multi_workfiles/file_open_form.py
We found that those DCCs based on PySide2 the `custom_actions` don't work as expected. 
When user clicks any of the menu options the signal is sent but the `_perform_action` method receives `False` instead of the action object.
The part of the code is located here:
https://github.com/shotgunsoftware/tk-multi-workfiles2/blob/master/python/tk_multi_workfiles/file_open_form.py#L300
We invested some time and tested this approach with successful results:
https://stackoverflow.com/questions/28318281/qaction-triggered-signal-is-not-passing-checked-parameter
Finally what we did:
Change:
`slot = lambda a=action: self._perform_action(a)`
With:
`slot = lambda a=action, checked=False: self._perform_action(a)`
And to avoid warning of assigning a lambda function to a variable, we then refined the …
=> Fix issue when running custom_actions in DCCs based on PySide2

python/tk_multi_workfiles/file_finder.py
The filter workfiles and publish hooks allow for customising data about the found files as well as filtering them out.
For example you can return a dictionary for each workfile or published file where you can adjust how they are renamed. However without this fix the `name` was ignored.
As an example if you had a workfiles filter hook that looked like this:
```python
import sgtk
HookClass = sgtk.get_hook_baseclass()
class FilterWorkFiles(HookClass):
def execute(self, work_files, **kwargs):
for a_workfile in work_files:
a_workfile["work_file"]["name"] = "bob"
return work_files
```
All workfiles would take on the name "bob", however without the fix the provided name would be ignored. With the fix it looks like this (all files were named "scene" previously):
=> SG-13565 Now uses the name passed from the filter hooks if provided

app.py, azure-pipelines.yml
Add **tk-alias** and **tk-vred** to the list of supported engines for the **launch_at_startup** option
=> [SHOT-2419] Have launch_at_startup for tk-multi-workfiles2 in Alias & VRED

python/tk_multi_workfiles/entity_tree/entity_tree_form.py
In the workfile breadcrumbs, use the entity display name instead of its type to make the navigation easier
will become
=> [SHOT-3316] Use display name instead of entity name in the Workfiles app

python/tk_multi_workfiles/ui/file_save_form.py, resources/file_save_form.ui
It now allows the user to save a file with a version number of up to 9999.
It was requested by users that we allow files with three decimal places, I figured giving four gives a bit more headroom just in case.
=> SG-17473 Increases the maximum save version value to 9999

tests/test_file_model.py
We were having intermittent failures on Windows with Python 2. For now we are disabling these tests on this environment.
=> SG-18283 Skips the flaky tests on Windows py2.

app.py, python/tk_multi_workfiles/work_files.py
@jfboismenu we'd like to add a parameter to the show dialog methods in the Workfiles2 app so that we can choose whether or not to open these dialogs in modal mode. There's a situation that came up for VRED when we need the Workfiles2 save dialog to be modal.
=> Add parameter to opening dialogs to specify modal or not.

app.py, codecov.yaml, hooks/scene_operation_tk-mari.py, info.yml, python/tk_multi_workfiles/actions/context_change_action.py, python/tk_multi_workfiles/actions/new_file_action.py, python/tk_multi_workfiles/browser_form.py, python/tk_multi_workfiles/context_change_form.py, python/tk_multi_workfiles/file_form_base.py, python/tk_multi_workfiles/file_open_form.py, python/tk_multi_workfiles/file_save_form.py, python/tk_multi_workfiles/my_tasks/my_tasks_form.py, python/tk_multi_workfiles/ui/file_open_form.py, python/tk_multi_workfiles/work_files.py, resources/file_open_form.ui
Adds a context change mode that means the open and save app options are replaced by a context change app.
In context change mode it contains the entity/context navigation windows, but no file select. Once a context has been picked you can press change context.
Tasks in the My tasks can be view can be double clicked to change context, when in context change mode.
**Refactoring of the Open, Save and Context change forms**
Previously, the open and save dialog derive from the same `FileFormBase` class, but that class makes no assumption about the UI, because the save and open dialogs have different UIs.
However this meant a bunch of duplicated code in the derived classes, because both UI's shared common functionality.
Instead of opting to make context change a "mode" of the open dialog, I …
=> SG-15693 add change context mode

python/tk_multi_workfiles/actions/new_file_action.py
If an Asset has no type set, this error being reported to the user in the UI did not include the more accurate error message that was showing up in the log file:
With this change, the dialog includes an extra details message (if there are any details) that are shown when clicking "Show Details":
See JIRA ticket for more detail: https://jira.autodesk.com/browse/SHOT-3474
=> SHOT-3474: Include extra details on "New File" action error

python/tk_multi_workfiles/file_open_form.py
* New Task dialog will pop up a second time after creating a new task due to duplicated signal connection.
* Removed signal connection in `FileOpenForm` as it is already connected in the parent class `FileFormBase`
=> SHOT-3645: Fix New Task dialog to only pop up once.

python/tk_multi_workfiles/file_model.py
* `removeRow` may cause the parent item to be deleted before we're done using it
* Use `takeRow` instead to remove the row without immediately deletign it -- we own the objec and do not keep reference to it, so garbage collection will free up the memory for us.
=> Fix 'Internal C++ object already deleted' on removing model rows.

azure-pipelines.yml, info.yml, python/tk_multi_workfiles/actions/interactive_open_action.py, python/tk_multi_workfiles/actions/open_file_action.py, python/tk_multi_workfiles/actions/open_publish_actions.py, python/tk_multi_workfiles/actions/open_workfile_actions.py, python/tk_multi_workfiles/browser_form.py, python/tk_multi_workfiles/file_list/file_list_form.py, python/tk_multi_workfiles/file_open_form.py, python/tk_multi_workfiles/framework_qtwidgets.py, python/tk_multi_workfiles/scene_operation.py, python/tk_multi_workfiles/ui/file_list_form.py, resources/build_resources.sh, resources/file_list_form.ui
* Add checkbox option next to "All Versions" to indicate if references should be checked on file open
* Only workfiles will be checked (not published), even if the option is toggled on
* If out of date references are found, a pop up dialog will be shown to ask the user how to handle them
=> [SHOT-4065] Check references on file open

hooks/scene_operation_tk-nuke.py, python/tk_multi_workfiles/scene_operation.py
This PR  fixes the issue with Nuke 13 on Windows failing to save when we have path definitions in the template starting with `0`, e.g.:
` shot_root: 08 sequences/{Sequence}/{Shot}/{Step`
=> SG-25609 Nuke 13 Crashes On Saving With a Custom Root Path

python/tk_multi_workfiles/entity_tree/entity_tree_form.py
* Without hiding the widget before shut down, the overlay spinner continues to fire timeout events to trigger animations.
=> SG-29395: Ensure that the overlay is hidden on shut down.

hooks/scene_operation_tk-nuke.py
- Follow up from #120.
- Detected when Nuke 13.2v5 crashes when saving in ShotGrid
- Nuke uses a `/` as a separator on all platforms (including Windows)
=> SG-29904 Update string replace to be compatible with Nuke on win32

.gitignore, hooks/user_login.py, python/tk_multi_workfiles/user_cache.py
To support DCCs running on Python 2 (Nuke 12).
Follow up from #124
=> SG-30567 Change string interpolation syntax

app.py
* tk-alias engine will be responsible for running the workfiles app at start up using the config setting `run_at_startup`
* tk-vred will also be removed from the workfiles2 supported engines list, to be consistent with tk-alias/Automotive apps
=> SHOT-4259: Remove tk-alias engine to run at startup

python/tk_multi_workfiles/file_list/file_list_form.py
This PR addresses a bug encountered during the testing of the config v1.6.1-rc4 . This bug caused a SyntaxError in older versions of Houdini (17.5.460) and Nuke (12.0v8), which both still rely on Python 2.7.
=> Config v1.6.1 - RC4: Python2 SyntaxError in tk-multi-workfiles2

python/tk_multi_workfiles/file_open_form.py, python/tk_multi_workfiles/framework_qtwidgets.py
* For style consistency across apps
* Fixes QMenu right-arrow display issue with PySide6
=> SHOT-4267: Use ShotgunMenu instead of QMenu

hooks/scene_operation_tk-houdini.py, hooks/ui_config.py, python/tk_multi_workfiles/actions/file_action_factory.py, python/tk_multi_workfiles/actions/interactive_open_action.py, python/tk_multi_workfiles/actions/open_file_action.py, python/tk_multi_workfiles/actions/open_publish_actions.py, python/tk_multi_workfiles/actions/open_workfile_actions.py, python/tk_multi_workfiles/actions/show_in_filesystem_action.py, python/tk_multi_workfiles/actions/show_in_shotgun_action.py, python/tk_multi_workfiles/context_change_form.py, python/tk_multi_workfiles/crash_dbg_form.py, python/tk_multi_workfiles/entity_models/deferred_model.py, python/tk_multi_workfiles/entity_models/extended_model.py, python/tk_multi_workfiles/entity_proxy_model.py, python/tk_multi_workfiles/file_finder.py, python/tk_multi_workfiles/file_item.py, python/tk_multi_workfiles/file_list/file_proxy_model.py, python/tk_multi_workfiles/file_model.py, python/tk_multi_workfiles/file_open_form.py, python/tk_multi_workfiles/file_save_form.py, python/tk_multi_workfiles/file_search_cache.py, python/tk_multi_workfiles/my_tasks/my_tasks_model.py, python/tk_multi_workfiles/scene_operation.py, python/tk_multi_workfiles/step_list_filter.py, python/tk_multi_workfiles/util.py, tests/python/workfiles2_test_base.py, tests/test_file_model.py, tests/test_user_filter_menu.py
- Following the steps from the plan checklist
=> SG-36835 - python2 removal

python/tk_multi_workfiles/file_model.py
The filter_work_files hook allows you to provide a thumbnail, but it's not used due to the `file_item.is_published` requirement in the FileModel._process_files method. This leaves us unable to show thumbnails for working files.
With this requirement removed, the filter_work_files hook can provide thumbnails as a file URI:
```python
class FilterWorkFiles(HookClass):
def execute(self, work_files, **kwargs):
for wf in work_files:
wf['work_file']['thumbnail'] = "file:///my_thumbnail.jpg"
return work_files
```
=> SG-30400 Retrieve thumbnails from any FileItem that has a 'thumbnail_path'

info.yml, python/tk_multi_workfiles/browser_form.py, python/tk_multi_workfiles/entity_models/extended_model.py, python/tk_multi_workfiles/entity_tree/entity_tree_proxy_model.py, python/tk_multi_workfiles/framework_qtwidgets.py, python/tk_multi_workfiles/my_tasks/my_tasks_form.py
Adds sorting for **My Tasks** left tab. It allows the user to provide custom fields in the `info.yml` file (assuming that they are valid fields to sort by).
**Heavily inspired by:**
- https://github.com/shotgunsoftware/tk-multi-workfiles2/pull/147
- https://github.com/shotgunsoftware/tk-multi-shotgunpanel/pull/67
- https://github.com/shotgunsoftware/tk-multi-shotgunpanel/pull/96
=> SG-2824 Sorting my tasks

python/tk_multi_workfiles/file_item.py
----
_NOTE: This is a replacement PR as we erroneously purged the repo from https://github.com/shotgunsoftware/tk-multi-workfiles2/pull/80 which should be closed in favor of this one)_
---
Fix for incorrect File Key being generated when `TemplateKeys` have additional parameters that require processing. Previously, the File Key would be generated using the raw values of the `TemplateKeys` - with this change it is generated with the processed value (using `str_from_value()`). 
The way this manifests itself, specifically when executing a File Save... The app uses the File Key to determine any matching files that are currently present on the filesystem. It then calculates the `version_number` by using the highest value for `version_number` from all files that exist with the given File Key, …
=> [SG-39990] Process the TemplateKey value before storing it
